[package]
name = "json_lint_example"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rls-data = "0.19.1"
serde_json = "1.0"

[build-dependencies]
rls-data = "0.19.1"
serde_json = "1.0"
